### ISSUE TITLE
Outdated Polling stations geocoded by TSE	

### ISSUE THREAD

**Issue by GoncalvesRD** [fdhidalgo/geocode_br_polling_stations#2]
The Polling Stations Geocoded by TSE data from Estado de Sāo Paulo Github are probably outdated. 

I noticed that there are too many NA in 'tse_lat' and 'tse_long' variables from geocoded_polliing_stations.csv.  72,754 NA from 94,984 total entries (ano=2018). 

In the same subset (ano=2018) the '[eleitorado_por_local_votacao_2018](https://cdn.tse.jus.br/estatistica/sead/odsele/eleitorado_locais_votacao/eleitorado_local_votacao_2018.zip)' data from the TSE Election Data Repository have 47,536 NA from 96,259 total entries.

Apart from that, Amazing job @fdhidalgo!

**Comment by fdhidalgo** [comment]
Thanks! And I didn't know about the updated data. Thank you for telling me and I will incorporate this more complete data. I'm sure this will improve the model as well.

**Comment by fdhidalgo** [comment]
I included the new data and re-generated the dataset and documentation to reflect this.
